### ISSUE TITLE
Fix report page url 

### ISSUE THREAD

**Issue by alexulven** [hackforla/311-data-archive#1158]
**Describe the bug**
When navigating to the reports page, if you type the address directly, the result is a blank page. To get to the reports page, you have to go to the map first and then click on the reports tab.

**To Reproduce**
1. Type in the address https://dev.311data.org/reports/
2. View the blank screen.

**Expected behavior**
The address above should lead directly to the reports page.

**Screenshots**
<img width="1254" alt="Screen Shot 2021-11-21 at 12 40 29 PM" src="https://user-images.githubusercontent.com/40405852/142773011-ac4b323e-b3c2-44ca-b300-529a2b77cd14.png">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] (chrome)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EchoProject** [comment]
Ask Adam if we can redirect the "reports" url link to the 311-data.org while we consider the following: 

Reports: create a reports home page that displays all reports with educational information.

**Comment by edwinjue** [comment]
Reports/dashboards will be frontend components in new NRD tech stack. Previously, this issue arose because the reports page was loaded in an iframe
