### ISSUE TITLE
Update Contact Us Form Fields to Match v1

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data-archive#1175]
### Overview
We need to update the v2 contact us form to match the fields from the v1 contact us form so that the messages are captured by our tracker. 

### Action Items
- [ ] {Developer to expand} 
- [ ] Add helper text to each field

### Resources/Instructions
v1 - https://311-data.org/contact
![Snip20220224_2](https://user-images.githubusercontent.com/20729686/155646239-b7d9b926-2ca9-4f3b-b129-98fa3bc2b29d.png)

v2 - https://dev.311-data.org/contact
![Snip20220224_1](https://user-images.githubusercontent.com/20729686/155646211-511d2a57-6332-4524-926e-61070c0dc097.png)

**Comment by shehjad-dev** [comment]
Hey there, I would love to work on this. ASSIGN this to me. I am available

**Comment by Unknownsentinel193** [comment]
Hi, is this issue still open? if Yes could you please assign this to me. I would work on it.
